f1 = open('text18-9.txt', errors='ignore')
k = f1.readlines()
k2 = len(k)
f2 = k
f1.close()
f4 = open('data_4.txt', 'a')
f4.write('\n')
print(f2, file=f4)
print('Количество элементов:', k2, file=f4)
f4.close()